### ISSUE TITLE
Laravel 4 version

### ISSUE THREAD

**Issue by jonasva** [awjudd/l4-feed-reader#12]
Which version can I use to get the Laravel 4 version of this 'l4'-feed reader? Is it possible to create a branch for that?

**Comment by awjudd** [comment]
Version 1.1.0.1 works in Laravel 4.  I haven't tried my Laravel 5 updates in a Laravel 4 based solution, they may still work, just the composer requirement is different.

**Comment by fbelal** [comment]
when i using version "awjudd/feed-reader": "1..1.0.1", the following errors come:

  Problem 1
    - Installation request for awjudd/feed-reader 1.1.0.1 -> satisfiable by awju
dd/feed-reader[1.1.0.1].
    - awjudd/feed-reader 1.1.0.1 requires simplepie/simplepie dev-master -> no m
atching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

**Comment by awjudd** [comment]
@fbelal You will have to set your `minimum-stability` to `dev` in your `composer.json` file.  The reason behind this is the fact that SimplePie hasn't made a release lately but there are bug fixes that went in.
