### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by subdesign** [awjudd/l4-feed-reader#13]
Trying to install 1.2.* on L5, but get composer error:
```
  Problem 1
    - Installation request for awjudd/feed-reader 1.2.* -> satisfiable by awjudd/feed-reader[1.2.0].
    - awjudd/feed-reader 1.2.0 requires simplepie/simplepie dev-master -> no matching package found.
```
Is it only me or..? thx

**Comment by awjudd** [comment]
Due to the slow releases of the simplepie project, I am forced to link the the "dev-master" branch (it is either that, or go on a 2+ year old release).  So, in order to use it, you need your minimum stability to be "dev".
