### ISSUE TITLE
Publishing config file not working in Laravel 5.1

### ISSUE THREAD

**Issue by dvdheiden** [awjudd/l4-feed-reader#14]
When running php artisan vendor:publish the config file doesn't get published and therefor isn't create in the config folder.

In registerConfiguration in the FeedReaderServiceProvider file, for Laravel 5.1 there should be something like:
```php
$this->publishes([
    $configPath = __DIR__ . '/../../config/config.php' => config_path('feed-reader.php'),
]);
```

This will create the config file.

**Comment by awjudd** [comment]
This should now be fixed with 1.3.0
