### ISSUE TITLE
 awjudd/feed-reader 1.2.0 requires simplepie/simplepie dev-master -> no matching package found.

### ISSUE THREAD

**Issue by gcphost** [awjudd/l4-feed-reader#16]
Latest simplepie:

        "simplepie/simplepie": "^1.3",

**Comment by awjudd** [comment]
The simplepie releases haven't been updated in more than 2 years because of that the application uses `dev-master`.

Once the following issue is closed (https://github.com/simplepie/simplepie/issues/390), then I will be able to finally move it off of `dev-master`.

**Comment by TareqElMasri** [comment]
The issue is closed and the problem stays.

**Comment by awjudd** [comment]
Thank you for informing me - I will test it all out within the next few days.

**Comment by awjudd** [comment]
@TareqElMasri - This has now been completed.  I have made a 1.3.0 release.
