### ISSUE TITLE
cannot install feed reader

### ISSUE THREAD

**Issue by xermus** [awjudd/l4-feed-reader#21]
After adding this to the require part of composer.json

```
awjudd/feed-reader": "1.3.*"
```

to my existing site and after running 

```
composer update
```

I get this error:

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for awjudd/feed-reader 1.3.* -> satisfiable by awjudd/feed-reader[1.3.0].
    - awjudd/feed-reader 1.3.0 requires simplepie/simplepie dev-master -> satisfiable by simplepie/simplepie[dev-master] but these conflict with your requirements or minimum-stability.

What do I have to do in order to install the feed reader to my existing project?

**Comment by awjudd** [comment]
This is a minimum stability issue.  You would need to reduce the minimum stability in your composer.json file.

That said, the reason why I had it set to use master has been resolved (they finally added a new release), so I will be updating the project within the next few days.

**Comment by xermus** [comment]
After you updated it, will it then work as inteded? (using what version) It would be a great things asap, seems like many people are looking forward for it.

**Comment by awjudd** [comment]
@xermus This should now be fixed.  Messed up the version number previously.
