### ISSUE TITLE
How can i sort data as popular, latest etc

### ISSUE THREAD

**Issue by Ravi-kavya01** [awjudd/l4-feed-reader#25]
Hi,
Is there any option we can sort data according to popularity, latest etc

Thanks

**Comment by awjudd** [comment]
@Ravi-kavya01 is this a function in SimplePie XML reader?

**Comment by awjudd** [comment]
@Ravi-kavya01 - Do you still need this functionality? If you do, I will need more information. If you don't, then I'll close this ticket.

**Comment by Ravi-kavya01** [comment]
Yes, I need it

**Comment by awjudd** [comment]
Closing issue as no extra information is provided.
