### ISSUE TITLE
Change minimum stability to stable

### ISSUE THREAD

**Issue by Ilyes512** [awjudd/l4-feed-reader#5]
Is there a reason why the minimum stability is `dev`? I need to set my stability from `stable` to `dev` just to use this library wish doesn't make sense.

**Comment by Anahkiasen** [comment]
Have simplepie still not released a new version? Have you opened an issue there for them to tag one?

**Comment by awjudd** [comment]
There is an open issue which is waiting on them to cut a release:
https://github.com/simplepie/simplepie/issues/390

Once that is complete, I will update this package to use the release.
