### ISSUE TITLE
Caching doesn't work?

### ISSUE THREAD

**Issue by Ricaz** [awjudd/l4-feed-reader#7]
I have caching enabled in the config, but it saves a new one everytime I call `FeedReader::read()` (so on every page load). I'm guessing the point caching is to not download the feed unless the cache is more 1hr old.

`'force-feed'` option is also `false`.

Am I doing something wrong?

**Comment by awjudd** [comment]
I will look into this one shortly.

**Comment by awjudd** [comment]
@Ricaz I wasn't able to reproduce this non-caching issue.  With caching enabled, the first run through is slow, then after that it is fast (because the data has been cached).
