### ISSUE TITLE
laravel 5 support?

### ISSUE THREAD

**Issue by lukeed** [awjudd/l4-feed-reader#9]
Plans?

**Comment by awjudd** [comment]
I definitely plan to - last time I tried to get the workspace working properly it wasn't working.  I'll see if I can work on the upgrade in the next week or so.

**Comment by lukeed** [comment]
Hey awjudd, any progress on this?
If i had a spare hour or two, I'd try to make it L5-ready. Sadly that time hasn't presented itself yet

**Comment by awjudd** [comment]
Sadly I've run into a similar lack of time.  I will try to do this within the next week.

**Comment by lukeed** [comment]
No rush on my end

**Comment by lukeed** [comment]
Thanks, good work!

**Comment by awjudd** [comment]
Awesome Thanks :)
